/* ODHYAY style: Quiet Editorial — content data is kept separate from page composition for a calm, maintainable reading experience. */
export const assets = { hero: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1800&q=88", cover1: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=88", cover2: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=88", cover3: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=88", mark: "" };
export type Book = { slug: string; title: string; author: string; category: string; pages: number; cover: string; description: string; featured?: boolean; added?: boolean; popular?: boolean; progress?: number };
export const books: Book[] = [
  { slug: "the-shape-of-silence", title: "The Shape of Silence", author: "Mira Sen", category: "দর্শন", pages: 184, cover: assets.cover1, description: "A gentle collection of essays on the spaces between what we say and what we choose to notice. A book about attention, stillness, and the small architecture of a meaningful day.", featured: true, popular: true, progress: 67 },
  { slug: "maps-for-the-unremembered", title: "Maps for the Unremembered", author: "Arunava Roy", category: "বাংলা সাহিত্য", pages: 238, cover: assets.cover2, description: "A lyrical journey through rooms, rivers, and the unreliable geography of memory. Roy writes with the quiet precision of someone returning home by another route.", added: true, popular: true },
  { slug: "a-small-atlas-of-stars", title: "A Small Atlas of Stars", author: "Leela Banerjee", category: "বিজ্ঞান", pages: 126, cover: assets.cover3, description: "An approachable meditation on the night sky, scale, and our place inside a universe that keeps asking better questions.", added: true },
  { slug: "the-warmth-of-ordinary-days", title: "The Warmth of Ordinary Days", author: "Nandita Bose", category: "আত্মউন্নয়ন", pages: 202, cover: assets.cover1, description: "Notes on making a life from the everyday: tea, work, friendship, and the generous practice of looking again.", popular: true },
  { slug: "letters-from-a-river", title: "Letters from a River", author: "S. Rahman", category: "ইতিহাস", pages: 164, cover: assets.cover2, description: "Fragments of a changing landscape told through the voices that lived beside it.", added: true },
  { slug: "the-long-way-home", title: "The Long Way Home", author: "Ishita Das", category: "উপন্যাস", pages: 310, cover: assets.cover3, description: "A quiet, searching novel about leaving, returning, and the things a familiar street remembers.", popular: true },
];
export const categories = ["বাংলা সাহিত্য", "উপন্যাস", "গল্প", "কবিতা", "বিজ্ঞান", "ইতিহাস", "দর্শন", "আত্মউন্নয়ন", "শিক্ষা", "জীবনী", "অন্যান্য"];
